language: csharp
mono: latest
dist: xenial
dotnet: 5.0.100

git:
  depth: false

if: NOT branch =~ ^develop/.*$ OR branch =~ ^develop/travis/.*$

cache:
  timeout: 300
  directories:
  - packages
  - $HOME/.nuget

script:
  - export PATH="$PATH:/home/travis/.dotnet/tools"
  - dotnet tool restore
  - dotnet fake run ./Build/setup.fsx
  - dotnet fake run ./Build/build.fsx