language: csharp
mono: latest
dotnet: 2.1.402
sudo: false

git:
  depth: false

if: NOT branch =~ ^develop/.*$ OR branch =~ ^develop/travis/.*$

cache:
  timeout: 300
  directories:
  - packages
  - $HOME/.nuget

script:
  - export PATH="$PATH:/home/travis/.dotnet/tools"
  - dotnet restore ./dotnet-fake.fsproj
  - dotnet fake run ./Build/setup.fsx
  - dotnet fake run ./Build/build.fsx