version: 5.9.3.{build}
branches:
  except:
  - /develop.*/
skip_tags: true
image: Visual Studio 2017
clone_depth: 2
environment:
  COVERALLS_REPO_TOKEN:
    secure: REZBaTQymYRQdGEJgpMw1O75r2pVJ7yNlhwLXwoj1NWaEYs5sTwpPdGlvjlWAf13
cache: 
  - packages -> **\packages.config
  - '%USERPROFILE%\.nuget\packages -> **\*.*proj'
nuget:
  disable_publish_on_pr: true
build_script:
- ps: >-
    $ErrorActionPreference = 'Continue'

    & dotnet restore dotnet-fake.fsproj

    & dotnet fake run .\Build\setup.fsx

    & dotnet fake run .\Build\build.fsx

    $save = $LASTEXITCODE
    
    $error.Clear()

    Write-Host "Exit code $save"

    if ($save -ne 0) { exit $save }
artifacts:
- path: _Packagin*\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: xkwBh+Yq1rXo/MzI5CdoGrLO8a3h73c3BaOFLQSgzE+uulMhOHYeHdPHXGWd9vRA
  on:
    branch: /release.*/